### ISSUE TITLE
LMDE 5 Latte Dock Install Error Synaptic Package Manager

### ISSUE THREAD

**Issue by just-grooving** [linuxmint/lmde-5-cinnamon-beta#11]
I installed LMDE 5 Beta yesterday.  When I tried to install Latte Dock via Synaptic, the install partially failed at the end of the installation.  I then tried to uninstall it via Synaptic, and it failed at the same spot again.  I then tried to remove everything for Latte Dock via command line, but I still  have a part of the dock showing up.

I am attaching screenshots of both install error message and the uninstall error message for Synaptic.
![latte dock error](https://user-images.githubusercontent.com/100726226/156243459-1a81c3fc-bb43-4214-b883-bfe2c710589c.png)
![latte dock error uninstall](https://user-images.githubusercontent.com/100726226/156243476-d8aedb54-6640-4e45-9226-92050dec651a.png)

**Comment by xenopeek** [comment]
If I try to install the offending package `software-properties-kde` it gives the same error and the package is not installed, but its dependencies are. Try on the terminal to run this command:
```
apt autoremove --purge
```
That will remove all the packages that were installed as a dependency but are no longer needed. If I do that after trying to install software-properties-kde it prompts:
```
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following packages will be REMOVED:
  python3-distro-info* python3-software-properties* software-properties-common* unattended-upgrades*
0 upgraded, 0 newly installed, 4 to remove and 0 not upgraded.
4 not fully installed or removed.
After this operation, 509 kB disk space will be freed.
Do you want to continue? [Y/n] 
```
But it may be a much longer list for you or not work at all as latte-dock effectively converts your LMDE 5 install from Cinnamon to KDE, seeing as latte-dock is for the Plasma desktop. latte-dock installs 400+ packages as dependencies.

**Comment by just-grooving** [comment]
Thank you. I tried that but the remnant of the dock still shows on the bottom of my monitor, can't get rid of it.  I use latte-dock without issues on another distro called Q4OS, which is also a debian 11 based.  However, it offers cinnamon as a second desktop to their trinity desktop.  I think maybe the trinity desktop may have some kde elements in it that allow latte dock to install correctly.

I will reinstall LMDE 5 tomorrow night  and try it with cario-dock to see how that works.  Too bad latte-dock doesn't work, it is a nice application.  But I don't want to try to pound a round peg into a square hole.

Sorry to be so long in responding, I have not been well.

You can go ahead and close this issue if you like.  If I run into a problem with cairo-dock I will open a new report.

Thank you.  I see your handle a lot on the LMDE forum on Linux Mint.

**Comment by xenopeek** [comment]
Happy to help. Trinity is a KDE 3 fork so likely as you say the developers made latte dock work with it.

If cairo dock doesn't work well you can try plank. There is a section on the support forums for docks and other eye candy, should you need help with it: https://forums.linuxmint.com/viewforum.php?f=212
