### ISSUE TITLE
I found some non-english text

### ISSUE THREAD

**Issue by enigma9o7** [linuxmint/lmde-5-cinnamon-beta#12]
In settings...

https://i.imgur.com/Jl8nlRV.png

**Comment by Jeremy7701** [comment]
This is a correct use of Lorem ipsum..., although its in Latin it's used to demonstrate what a piece of unknown text could look like.

See [https://en.wikipedia.org/wiki/Lorem_ipsum](https://en.wikipedia.org/wiki/Lorem_ipsum)

**Comment by enigma9o7** [comment]
Ah.  Well it is not obvious to me it was sample text, I assumed it was some type of description/instructions.... and since it is not available to copy and paste into a translator (highlight wont work) I couldn't even figure out what it means...
