### ISSUE TITLE
Does "TeXInfo" need to be in the menu? The menu launcher for the `info` command

### ISSUE THREAD

**Issue by vegam57** [linuxmint/lmde-5-cinnamon-beta#13]
Texinfo
LMDE5
![スクリーンショット 2022-03-02 06-18-59](https://user-images.githubusercontent.com/78515193/156251307-6bcb38ce-e3eb-4827-8b39-87ebe6a76c2b.png)

**Comment by Jeremy7701** [comment]
This gives the same result as typing `info` (without parameters) into a terminal screen.

**Comment by clefebvre** [comment]
This should be hidden indeed.

**Comment by clefebvre** [comment]
Fixed
