### ISSUE TITLE
Privileges given to users

### ISSUE THREAD

**Issue by vegam57** [linuxmint/lmde-5-cinnamon-beta#14]
Privileges given to users
Is this correct for the group difference between LMDE5 and LM203? 
![スクリーンショット 2022-03-02 09-08-56](https://user-images.githubusercontent.com/78515193/156271193-abc965e0-2d46-484a-adff-d6b0d51e91b8.png)

**Comment by Jeremy7701** [comment]
LMDE5 (admin) appears to be have exactly the same groups as LMDE4 - (ignore the vboxsf group as that is additional).

LMDE4 groups:-
![Screenshot from 2022-03-02 13-49-09](https://user-images.githubusercontent.com/52585119/156375162-d6a058d6-3257-4701-8481-5231ebb07442.png)

**Comment by vegam57** [comment]
> LMDE5 (admin) appears to be have exactly the same groups as LMDE4 - (ignore the vboxsf group as that is additional).

I understand that if it is the same as LMDE4, there should be no problem.
Thank you
