### ISSUE TITLE
Drives in the left-side bar with the "&" symbol in their label have an incorrectly-displayed tooltip on mouseover

### ISSUE THREAD

**Issue by NintendoManiac64** [linuxmint/lmde-5-cinnamon-beta#15]
If your drive has an "&" symbol in the partition label and you hover your mouse cursor over the according partition in the left-side bar in Thunar, the tooltip that is displayed will be incorrect.

The incorrect tooltip will either show the text from the previous tooltip instead (this occurs if you keep your cursor within the left-side bar) or will show a blank tooltip with no text at all as if the text was nothing more than a space as in the spacebar (see attached screenshot - this occurs if you move your cursor from the folder-view area and directly onto the according partition with the "&" symbol)

This was tested on live LMDE 5 right after boot - all I did was open the "Mint" home folder and connect my 4GB FAT32 USB flash drive with the label "MISC & CRAP" (refer to the following screenshot; that weird pale rectangle below the highlighted "MISC & CRAP" USB flash drive is in fact the tooltip):
![screenshot](https://user-images.githubusercontent.com/11896003/156297855-38109afd-04ef-4512-90c7-0776a4a898bc.png)

**Comment by xenopeek** [comment]
Thanks for reporting. The Thunar maintainer https://gitlab.xfce.org/xfce/thunar/-/issues/734#note_43233 notes this looks to be a toolkit issue. Closing as upstream.
