### ISSUE TITLE
Missing "remove install media" during install

### ISSUE THREAD

**Issue by Jeremy7701** [linuxmint/lmde-5-cinnamon-beta#2]
In a VM install, using defaults:-
Should display "Remove install media" and reboot - but no message was shown.
Needed to press enter to make it continue.

This error seems widespread over various installs - so a warning in the install instructions would seem to be OK.

**PS Fantastic to see thumbnailing working for EPUB files!!!**

**Comment by lumixdeee** [comment]
Confirmed, problem also present on 32 bit iso installed on bare metal.

**Comment by BenTrabetere** [comment]
Confirmed, problem also present on 64-bit ISO installed on bare metal.

**Comment by Ethanol6** [comment]
See Clem's comments here: https://community.linuxmint.com/iso/view/670

**Comment by clefebvre** [comment]
Fixed in next ISO.
