### ISSUE TITLE
Error on opening LMDE 5 on Boxes

### ISSUE THREAD

**Issue by kangal3632** [linuxmint/lmde-5-cinnamon-beta#20]
I am running LMDE 5 in Boxes on Linux Mint 20.3. The 20.3  system follows. After I log on to LMDE 5, an error pops up saying: check your  videos drivers. Your system is currently running without video hardware acceleration. You may experience poor performance and high CPU usage. Screen shot is attached.

System:    Kernel: 5.13.0-30-generic x86_64 bits: 64 compiler: N/A Desktop: Cinnamon 5.2.7 
           wm: muffin dm: LightDM Distro: Linux Mint 20.3 Una base: Ubuntu 20.04 focal 
Machine:   Type: Laptop System: LENOVO product: 82C4 v: Lenovo V14-IIL serial: <filter> Chassis: 
           type: 10 v: Lenovo V14-IIL serial: <filter> 
           Mobo: LENOVO model: LNVNB161216 v: SDK0J40700 WIN serial: <filter> UEFI: LENOVO 
           v: DKCN49WW date: 10/26/2020 
Battery:   ID-1: BAT0 charge: 25.9 Wh condition: 34.3/35.0 Wh (98%) volts: 7.8/7.5 
           model: SMP L16M2PB2 serial: <filter> status: Discharging 
CPU:       Topology: Quad Core model: Intel Core i5-1035G1 bits: 64 type: MT MCP arch: Ice Lake 
           rev: 5 L2 cache: 6144 KiB 
           flags: avx avx2 lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 19046 
           Speed: 3340 MHz min/max: 400/3600 MHz Core speeds (MHz): 1: 3446 2: 2681 3: 2947 
           4: 2969 5: 3503 6: 3025 7: 2777 8: 3175 
Graphics:  Device-1: Intel vendor: Lenovo driver: i915 v: kernel bus ID: 00:02.0 
           chip ID: 8086:8a56 
           Display: x11 server: X.Org 1.20.13 driver: modesetting unloaded: fbdev,vesa 
           resolution: 1920x1080~60Hz 
           OpenGL: renderer: Mesa Intel UHD Graphics (ICL GT1) v: 4.6 Mesa 21.2.6 
           direct render: Yes 
Audio:     Device-1: Intel Smart Sound Audio vendor: Lenovo driver: snd_hda_intel v: kernel 
           bus ID: 00:1f.3 chip ID: 8086:34c8 
           Sound Server: ALSA v: k5.13.0-30-generic 
Network:   Device-1: Qualcomm Atheros QCA9377 802.11ac Wireless Network Adapter vendor: Lenovo 
           driver: ath10k_pci v: kernel port: 5040 bus ID: 01:00.0 chip ID: 168c:0042 
           IF: wlp1s0 state: up mac: <filter> 
           Device-2: Qualcomm Atheros type: USB driver: btusb bus ID: 1-10:4 chip ID: 0cf3:e500 
Drives:    Local Storage: total: 1.38 TiB used: 151.83 GiB (10.8%) 
           ID-1: /dev/nvme0n1 vendor: Samsung model: MZVL2512HCJQ-00BL7 size: 476.94 GiB 
           speed: 63.2 Gb/s lanes: 4 serial: <filter> 
           ID-2: /dev/sda vendor: Seagate model: ST1000LM035-1RK172 size: 931.51 GiB 
           speed: 6.0 Gb/s serial: <filter> 
Partition: ID-1: / size: 467.96 GiB used: 55.57 GiB (11.9%) fs: ext4 dev: /dev/nvme0n1p2 
USB:       Hub: 1-0:1 info: Full speed (or root) Hub ports: 12 rev: 2.0 chip ID: 1d6b:0002 
           Device-1: 1-5:2 info: Chicony Integrated Camera type: Video driver: uvcvideo rev: 2.0 
           chip ID: 04f2:b624 
           Device-2: 1-9:3 info: Pixart Imaging PixArt 2.4G Wireless Mouse type: Mouse,Keyboard 
           driver: hid-generic,usbhid rev: 2.0 chip ID: 093a:3701 
           Device-3: 1-10:4 info: Qualcomm Atheros type: Bluetooth driver: btusb rev: 2.0 
           chip ID: 0cf3:e500 
           Hub: 2-0:1 info: Full speed (or root) Hub ports: 6 rev: 3.1 chip ID: 1d6b:0003 
Sensors:   System Temperatures: cpu: 66.0 C mobo: N/A 
           Fan Speeds (RPM): N/A 
Repos:     No active apt repos in: /etc/apt/sources.list 
           Active apt repos in: /etc/apt/sources.list.d/lightzone-team-lightzone-focal.list 
           1: deb http: //ppa.launchpad.net/lightzone-team/lightzone/ubuntu focal main
           Active apt repos in: /etc/apt/sources.list.d/official-package-repositories.list 
           1: deb http: //packages.linuxmint.com una main upstream import backport #id:linuxmint_main
           2: deb http: //archive.ubuntu.com/ubuntu focal main restricted universe multiverse
           3: deb http: //archive.ubuntu.com/ubuntu focal-updates main restricted universe multiverse
           4: deb http: //archive.ubuntu.com/ubuntu focal-backports main restricted universe multiverse
           5: deb http: //security.ubuntu.com/ubuntu/ focal-security main restricted universe multiverse
           6: deb http: //archive.canonical.com/ubuntu/ focal partner
Info:      Processes: 277 Uptime: 3h 52m Memory: 19.34 GiB used: 6.60 GiB (34.1%) Init: systemd 
           v: 245 runlevel: 5 Compilers: gcc: 9.3.0 alt: 9 Client: Unknown python3.8 client 
           inxi: 3.0.38 
[/code
![Screenshot from 2022-03-03 10-45-07](https://user-images.githubusercontent.com/100831976/156523072-8b509d6f-928d-408a-9c40-14a95ed3129e.png)
]

**Comment by leigh123linux** [comment]
Gnome-boxes or libvirt have never provided proper 3D graphics drivers.

**Comment by kangal3632** [comment]
Thank you, I was not aware of this issue.

**Comment by xenopeek** [comment]
The message is Cinnamon informing you that 3d hardware acceleration is not available. That is not unexpected for Boxes, and it's not an error. I think Boxes defaults to use the QXL video driver, which is quite fast but doesn't do 3d hardware acceleration. Setting up 3d hardware acceleration on Boxes may be possible—there are various options—but it is a rabbit hole to figure it out and it likely will also require you to install things on the guest OS.

**Comment by kangal3632** [comment]
Vincent,

Thank you. I am not doing intensive graphics work but wanted to aid in the
betterment of LMDE 5.

I LOVE my Mint 20.3 but I would feel very comfortable switching when the
time is right.

**Comment by C8forT** [comment]
FYI, LMDE 5 works well with Virt-manager, which also is a GUI for qemu/KVM but provides more installation options.  The installation options that worked for me are as follows: 
1.  In Video, change "QXL" to "VirtIo" in the drop-down menu, and check the box "3D acceleration" so that you see a check mark, not a dash.
2. In Display Spice, set "Listen type" to "None", check the box "OpenGL", then select "Auto".
