### ISSUE TITLE
hardware: LMDE5 on Boxes (Virtual Machine) cannot find Bluetooth

### ISSUE THREAD

**Issue by kangal3632** [linuxmint/lmde-5-cinnamon-beta#22]
LMDE 5 on my Boxes Virtual Machine cannot find the Bluetooth adapter.  I had a similar issue with my Linux Mint 20,3 but one day it started working after I loaded MX -21 Linux on the virtual machine.   The system report for Linux Mint 20.3 shows: Device-3: 1-10:4 info: Qualcomm Atheros type: Bluetooth driver: btusb rev: 2.0   chip ID: 0cf3:e500 

I do not have this issue with MX-21 running on my Boxes Virtual Machine.

System Report for LMDE 5 on VM (Boxes)
System:    Kernel: 5.10.0-11-amd64 x86_64 bits: 64 compiler: gcc v: 10.2.1 Desktop: Cinnamon 5.2.7  tk: GTK 3.24.24 wm: muffin dm: LightDM Distro: LMDE 5 Elsie base: Debian 11.2 bullseye 
Machine:   Type: Kvm System: QEMU product: Standard PC (i440FX + PIIX, 1996) v: pc-i440fx-focal  serial: <filter> Chassis: type: 1 v: pc-i440fx-focal serial: <filter>   Mobo: N/A model: N/A serial: N/A BIOS: SeaBIOS v: 1.13.0-1ubuntu1.1 date: 04/01/2014 
CPU:       Info: Quad Core model: Intel Core i5-1035G1 bits: 64 type: MT MCP arch: Ice Lake rev: 5  L2 cache: 16 MiB  flags: avx avx2 lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 19046 Speed: 1190 MHz min/max: N/A Core speeds (MHz): 1: 1190 2: 1190 3: 1190 4: 1190 5: 11906: 1190 7: 1190 8: 1190 
Graphics:  Device-1: Red Hat QXL paravirtual graphic card driver: qxl v: kernel bus ID: 00:02.0 
           chip ID: 1b36:0100 
Display: x11 server: X.Org 1.20.11 driver: loaded: qxl note: n/a (using device driver) 
           unloaded: fbdev,modesetting,vesa resolution: 1024x768~60Hz s-dpi: 96 
           OpenGL: renderer: llvmpipe (LLVM 11.0.1 256 bits) v: 4.5 Mesa 20.3.5 compat-v: 3.1 
           direct render: Yes 
Audio:     Device-1: Intel 82801FB/FBM/FR/FW/FRW High Definition Audio 
           vendor: Red Hat QEMU Virtual Machine driver: snd_hda_intel v: kernel bus ID: 00:04.0 
           chip ID: 8086:2668 
           Sound Server: ALSA v: k5.10.0-11-amd64 
Network:   Device-1: Intel 82371AB/EB/MB PIIX4 ACPI vendor: Red Hat Qemu virtual machine 
           type: network bridge driver: piix4_smbus v: N/A port: c200 bus ID: 00:01.3 
           chip ID: 8086:7113 
           Device-2: Realtek RTL-8100/8101L/8139 PCI Fast Ethernet Adapter 
           vendor: Red Hat QEMU Virtual Machine driver: 8139cp v: 1.3 port: c000 bus ID: 00:03.0 
           chip ID: 10ec:8139 
           IF: ens3 state: up speed: 100 Mbps duplex: full mac: <filter> 
Drives:    Local Storage: total: 20 GiB used: 7.46 GiB (37.3%) 
           ID-1: /dev/sda vendor: QEMU model: HARDDISK size: 20 GiB speed: <unknown> 
           serial: <filter> 
Partition: ID-1: / size: 17.5 GiB used: 7.09 GiB (40.5%) fs: ext4 dev: /dev/sda2 
Swap:      ID-1: swap-1 type: partition size: 2.05 GiB used: 378.4 MiB (18.0%) priority: -2 
           dev: /dev/sda1 
USB:       Hub-1: 1-0:1 info: Full speed (or root) Hub ports: 2 rev: 1.1 speed: 12 Mb/s 
           chip ID: 1d6b:0001 
           Device-1: 1-1:2 info: Gemalto (was Gemplus) GemPC433-Swap type: Smart Card driver: N/A 
           rev: 1.1 speed: 12 Mb/s chip ID: 08e6:4433 
           Hub-2: 2-0:1 info: Full speed (or root) Hub ports: 6 rev: 2.0 speed: 480 Mb/s 
           chip ID: 1d6b:0002 
           Hub-3: 3-0:1 info: Full speed (or root) Hub ports: 2 rev: 1.1 speed: 12 Mb/s 
           chip ID: 1d6b:0001 
           Hub-4: 4-0:1 info: Full speed (or root) Hub ports: 2 rev: 1.1 speed: 12 Mb/s 
           chip ID: 1d6b:0001 
Sensors:   Message: No sensors data was found. Is sensors configured? 
Repos:     Packages: apt: 2030 
           No active apt repos in: /etc/apt/sources.list 
           No active apt repos in: /etc/apt/sources.list.d/additional-repositories.list 
           Active apt repos in: /etc/apt/sources.list.d/home:ktgw0316:LightZone.list 
           1: deb http: //download.opensuse.org/repositories/home:/ktgw0316:/LightZone/Debian_11/ /
           Active apt repos in: /etc/apt/sources.list.d/official-package-repositories.list 
           1: deb http: //packages.linuxmint.com elsie main upstream import backport #id:linuxmint_main
           2: deb https: //deb.debian.org/debian bullseye main contrib non-free
           3: deb https: //deb.debian.org/debian bullseye-updates main contrib non-free
           4: deb http: //security.debian.org bullseye-security main contrib non-free
           5: deb https: //deb.debian.org/debian bullseye-backports main contrib non-free
Info:      Processes: 223 Uptime: 1h 18m Memory: 1.93 GiB used: 749.7 MiB (37.8%) Init: systemd 
           v: 247 runlevel: 5 Compilers: gcc: 10.2.1 alt: 10 Client: Unknown python3.9 client 
           inxi: 3.3.01 
[/code]

**Comment by clefebvre** [comment]
I'll close this since it doesn't lead to a bug fix resolution. It looks like a hardware support issue, I'd suggest troubleshooting it on the forums.

**Comment by kangal3632** [comment]
Thank you.

I/ll see what happens when I load LMDR 5 on my work machine when the final
release comes out.

Best Regards,

Gary L. Caldwell
Cell: +90 539 820 1660
VOIP: +1 703 994 4387
Skype: kangal3632
