### ISSUE TITLE
"Stuck" program window if you double-click on a .deb file and then select install but then, rather than input your password, you click "cancel"

### ISSUE THREAD

**Issue by NintendoManiac64** [linuxmint/lmde-5-cinnamon-beta#24]
As described in the lengthy title, simple double-click on any .deb file, click "Install" but then, when it asks for your password, click "cancel"

The existing program window for installing the .deb will then become "stuck" in that you can't close it or otherwise interact with it.

**EDIT**: alternatively you can click the X button on the password window rather than cancel and the same issue will occur

**Comment by Jeremy7701** [comment]
What program are you using to install the deb file?
For example, are you using `Gdebi` against a deb file which couldn't be installed from a secure repository?

**Comment by NintendoManiac64** [comment]
Uhh, I'm just using the default that LMDE 5 comes with.  I tested using a completely fresh installation of LMDE 5 whereby, immediately after first boot, I just double-clicked on a .deb file that I have stored on a different drive and it comes up in whatever package installer LMDE 5 uses by default.

This also wasn't specific to a single .deb file and happens regardless of the .deb from what I can tell. 

Also I would imagine that clicking the X on the password window would cause the exact same issue - I'll test it and report back.

(and because the issue relies on the user clicking "cancel" on the password entry window, it also doesn't work in a live session since the password entry window never even appears in such a situation)

**Comment by Jeremy7701** [comment]
Reproduced.
It is indeed Gdebi with the bug.
You can "recover" with `killall gdebi-gtk`

**Comment by NintendoManiac64** [comment]
I also just tested and confirmed that it occurs even if you click the X button on the password window rather than cancel.

**Comment by NerdsMaxx** [comment]
For me, it didn't even open gdebi. So I installed gdebi from repository Debian and worked. Now work good.

**Comment by Jeremy7701** [comment]
> For me, it didn't even open gdebi. So I installed gdebi from repository Debian and worked. Now work good.

Does it replicate the bug or does it work correctly without any window lockup?
I tried `gdebi` in LMDE4 and it works correctly by putting up a dialog box if you try to cancel or bypass the authorisation step.

**Comment by NerdsMaxx** [comment]
Sorry for late. 
It works normally from repository Debian. From repository Linux Mint, no, It didn't even open.
