### ISSUE TITLE
W: plymouth: The plugin label.so is missing on kernel build of nvidia-driver (460.91.03-1)

### ISSUE THREAD

**Issue by Acheron17** [linuxmint/lmde-5-cinnamon-beta#26]
Keep seeing this message when Setting up nvidia-driver (460.91.03-1) .  Here is the complete text:

Setting up nvidia-driver (460.91.03-1) ...
Processing triggers for libc-bin (2.31-13+deb11u2) ...
Processing triggers for initramfs-tools (0.140) ...
update-initramfs: Generating /boot/initrd.img-5.10.0-11-amd64
W: plymouth: The plugin label.so is missing, the selected theme might not work a
s expected.
W: plymouth: You might want to install the plymouth-themes package to fix this.
Processing triggers for update-glx (1.2.0) ...
Processing triggers for glx-alternative-nvidia (1.2.0) ...
update-alternatives: using /usr/lib/nvidia to provide /usr/lib/glx (glx) in auto
 mode
Processing triggers for glx-alternative-mesa (1.2.0) ...
Processing triggers for libc-bin (2.31-13+deb11u2) ...
Processing triggers for initramfs-tools (0.140) ...
update-initramfs: Generating /boot/initrd.img-5.10.0-11-amd64
W: plymouth: The plugin label.so is missing, the selected theme might not work a
s expected.
W: plymouth: You might want to install the plymouth-themes package to fix this.

Note: System was installed without GRUB.
Is there a plan to fix this before stable release or we'll just have to live with it?
Thanks.

**Comment by Jeremy7701** [comment]
You can fix this by installing the plymouth-themes package.
Similar messages are generated when generating modules for Virtual Box extensions.

It really ought to go in LMDE5 since it's part of LMDE4...

**Comment by mtwebster** [comment]
There's another beta iso coming - this will be fixed (missing plymouth-label).
