### ISSUE TITLE
Cannot have a "quiet" boot

### ISSUE THREAD

**Issue by lumixdeee** [linuxmint/lmde-5-cinnamon-beta#27]
32 bit lmde5 in legacy mode

in /etc/default/grub
change GRB_CMDLINE_LINUX_DEFAULT to "quiet"

update-grub and reboot

Expecting to see plymouth boot messages
Observed splash screen instead

**Comment by clefebvre** [comment]
Set it in /etc/default/grub.d/90_custom.conf to override /etc/default/grub.d/50_lmde.conf.

**Comment by lumixdeee** [comment]
Thank you, commented out that line from 50_lmde.conf now it works as expected.
