### ISSUE TITLE
LMDE 5 Firefox does not respect an existing restored profile on startup

### ISSUE THREAD

**Issue by Acheron17** [linuxmint/lmde-5-cinnamon-beta#28]
In the past, LMDE had used an ESR version of Firefox.  When Firefox was started up for the first time it insisted on creating an ESR profile.  I was delighted to know LMDE 5 would use a Debian package from Mint and would discontinue the ESR version.  After Mint 20.x is installed, I restore the existing backed up profile to the system in ~/.mozilla and then start Firefox with no issues.

The issue encountered in LMDE 5's Firefox was it insists in creating a new profile on startup instead of respecting the existing profile.  Why?  Since Linux Mint is creating this package, can this be fixed?

**Comment by mtwebster** [comment]
If upgrading from the LMDE4 firefox esr (discontinued at ff 93 I think), you'll have to open the profile manager and re-select the old esr profile - after that it should be fine.  If upgrading from 95+, it should be an automatic migration.

This has to do with how firefox generates the profile ID internally. We were able to correct it internally while we were building firefox, but not any longer.

**Comment by Acheron17** [comment]
Just to clarify, I was not upgrading.  Just moving the same profile from Firefox 97 "Una" to Firefox 97 "Elsie"  It should be an automatic migration.

**Comment by mtwebster** [comment]
It's not, for the same reason - In Mint, firefox is in /lib. In LMDE, it has always been in /opt. 

The profile names (like `wxbqhkgj.default` for example) are generated strings, and are based partly on the location of the firefox executable. If you installed firefox in 5 different locations, it would create 5 separate profiles.

Changing it to /lib would have forced everyone on LMDE to fix their profiles when they upgraded to non-esr firefox.

**Comment by Acheron17** [comment]
Thank you for the explanation.  To solve the issue, I used "about:profiles" and selected the existing restored profile.
