### ISSUE TITLE
Cannot close synaptic while reloading cache in software sources unless the user clicks "cancel" (thereby requiring the user to then re-enter the key or repository a second time)

### ISSUE THREAD

**Issue by NintendoManiac64** [linuxmint/lmde-5-cinnamon-beta#29]
If you open "Software Sources" via synaptic like so:
![1](https://user-images.githubusercontent.com/11896003/156915936-56b338c8-f8f5-47d6-8711-5cf14361120d.png)

And then, without closing the synaptic program window, go and add a new key or repository to "software sources"; for example, I added the following [key for Pale Moon on Debian 10](https://software.opensuse.org/download.html?project=home:stevenpusser&package=palemoon) (yes I realize that LMDE 5 is based off of Debian 11, but this issue should occur regardless):

`https://download.opensuse.org/repositories/home:stevenpusser/Debian_10/Release.key`

From there it starts to begin updating the cache but then stops at the point where it says "waiting for synaptic to exit":
![2](https://user-images.githubusercontent.com/11896003/156916152-627e79c7-3b82-44a7-9a72-cf3d19e84f6a.png)

But the problem is that, as long as that "Updating Cache" window is open, you can't actually close synaptic - clicking X on the synaptic window at that moment does nothing, forcing the user to instead click "cancel" on the "Updating Cache" window, at which point _then_ you can go about first closing synaptic, but then the user has to re-enter whatever key or repository they were originally trying to enter.

**Comment by Jeremy7701** [comment]
Is there a problem in waiting for the dialog box indicating the progress of the cache update to finish?

**Comment by NintendoManiac64** [comment]
The dialog box says it's waiting for synaptic to close and will not progress any farther until synaptic is closed.

...but, in the given scenario, clicking (X) on the synaptic window does not actually close the synaptic window - the user has to first click "Cancel" on the dialog box.

**Comment by mtwebster** [comment]
This is because synaptic launches mintsources (and waits for it to finish)

Then, mintsources triggers refresh dialog (and waits for it to finish).

This all ensures you don't interact with synaptic while the database it relies upon is possibly being updated, and is a good idea. 

I don't think not being able to close the synaptic window during the update is sufficient reason to change this - it's a pretty minor inconvenience, and the change could cause problems with synaptic until it's restarted.

**Comment by NintendoManiac64** [comment]
On farther testing, I just realized that you cannot close synaptic _anytime_ that the "software sources" window is open if you opened it through synaptic via Settings -> Repository, not just when the "reloading cache" window is open.

Does this by chance warrant re-opening this issue, or should I submit a new issue for that?  Or is that still considered "not enough of a problem"?

It's just that such an issue makes accessing software sources through synaptic almost useless because, if you try to change any software sources settings, it needs to then reload the cache which requires you to close synaptic but you can't close synaptic until you first close software sources at which point you then need to manually open software sources _again_ but directly through Mint's application menu rather than through synaptic in order to then implement whatever change you intended.

**Comment by mtwebster** [comment]
Sorry - I completely stopped paying attention to what the dialog was actually saying - yes this is a bit useless.
