### ISSUE TITLE
Alt+Mouse not working past top of screen in installer

### ISSUE THREAD

**Issue by lumixdeee** [linuxmint/lmde-5-cinnamon-beta#3]
Testing 32 bit lmde 5 iso
Xrandr Alt+mouse stops at top of screen.
Edit:  installer only, actual system ok.

**Comment by xenopeek** [comment]
I have no trouble with 32 bit LMDE 5 ISO to use alt+mouse to move general windows above top of the screen. Edited: but specifically the installer window, that indeed won't move up. Only the titlebar can be moved up above the screen, the rest of the window refuses to move up.

Same for 64 bit ISO; the installer window can't be moved up above top of the screen, only the titlebar.

**Comment by mtwebster** [comment]
This seems to happen on all 'client decorated' windows in Cinnamon - for example the same thing happens with the calculator app.

**Comment by xenopeek** [comment]
I tested the same in MATE and Xfce, there it doesn't happen. Edit: it also happens on Linux Mint 20.3 Cinnamon

**Comment by lumixdeee** [comment]
A question if I may? Would I be able to install an update to this using the live iso, and enjoy?

If so, how can I get an alert when it's available please?

**Comment by clefebvre** [comment]
It's coming today @minuxlintebiandedition as a cinnamon/muffin update.

**Comment by lumixdeee** [comment]
Thank you, I just booted the 32 bit iso and applied the updates (minus kernel, firefox, thunderbird).
Still cannot drag installer window past top of screen.

There are rather a lot of updates including a new kernel, is there any plan to issue an updated beta iso?

**Comment by xenopeek** [comment]
@minuxlintebiandedition after installing the cinnamon-muffin update to version 5.2.1+elsie through Update Manager you need to restart Cinnamon, to use the new version. Two ways you can do that:

- Log out and log back in (username 'mint', just press Enter for the password);
- or press Alt+F2 to open the run dialog, type 'r' (single letter r) and press Enter to restart Cinnamon.

After restarting Cinnamon you should be able to move the installer window up above the top of the screen further.

**Comment by lumixdeee** [comment]
Success!
Logged out and back in again, able to ALT+mouse and drag window past top of screen.
