### ISSUE TITLE
Cannot remove nemo-preview

### ISSUE THREAD

**Issue by lumixdeee** [linuxmint/lmde-5-cinnamon-beta#30]
Further to this : https://github.com/linuxmint/nemo-extensions/issues/441

_"Linuxmint mate 20.2 live iso

Installed nemo-preview.
Expected it to work like it does in cinnamon, which also uses mate-panel and libwnck.
nemo-preview should suppress libwnck tooltips to prevent clashing.

Also reproduced problem in lmde5 32 and 64 with mate-panel and nemo-preview."_

Now using lmde5 beta 32 bit ISO, cannot find any way to stop nemo-preview appearing. I have remove nemo-preview, and everything else I can find that might be involved but the preview still appears.

![Screenshot from 2022-03-06 10-43-17](https://user-images.githubusercontent.com/42706563/156922278-efb0a29d-b74d-46a8-aa84-e8e270ba1b10.png)

**Comment by Jeremy7701** [comment]
nemo-preview gives a preview of a selected file when you press the space bar for certain filetypes ( press space again to remove it).

Is your problem related only to the way the yellow tooltips are shown?

It doesn't appear to be present in standard 64 bit LMDE5.

**Comment by mtwebster** [comment]
This is a mate-panel bug and has nothing to do with nemo-preview.

You were answered here: https://github.com/mate-desktop/mate-panel/issues/534

Cinnamon has nothing to do with mate or mate-panel.

**Comment by lumixdeee** [comment]
I thought nemo-preview was he little picture of a window you see on hover over it's window list entry.
If not nemo-preview, then what is causing that little picture? It has only stated appearing in bullseye.

Quite separately, the yellow tooltip does nothing for anyone but get in the way.

How can this issue be resolved? 

The problem does occur in standard 64 bit lmde5 if using a mate desktop session

**Comment by mtwebster** [comment]
You can submit a patch to libwnck.

mate-panel window applet creates the little picture, but libwnck tells it when to do this.

This is definitely not an LMDE5 beta issue either.
