### ISSUE TITLE
Disks title bar

### ISSUE THREAD

**Issue by LittleScriptMan** [linuxmint/lmde-5-cinnamon-beta#32]
The Gnome Disks title Bar displays incorrectly when buttons are placed on left side and police in large size. The Close button does not appear. As it works fine in LMDE4 / Cinnamon 5.0.7, so doesn't seem related to Gnome.
Police and Size for window title:  Sans Bold 16

I forgot something that can be important : I'm french so the string displayed is not Disks but Disques (7 chars instead of 5)

I also found that if i enlarge the left panel to the right, the close control appears again, but enlarging the whole window to the left has no effect..

**Comment by xenopeek** [comment]
I think this is a problem in Disks itself. The button placement jumps all over the place depending on which theme you're using. Even with Adwaita theme it's not displaying the buttons correctly: the close button is off the left edge of the window. The same happens on Debian 11 Gnome.

**Comment by clefebvre** [comment]
It's an upstream bug https://gitlab.gnome.org/GNOME/gnome-disk-utility/-/issues/148.

**Comment by clefebvre** [comment]
Fixed in 3.38.2+mint1
