### ISSUE TITLE
Thingy; Thumbnail perfection is different between the two 

### ISSUE THREAD

**Issue by vegam57** [linuxmint/lmde-5-cinnamon-beta#33]
Thingy
Thumbnail perfection is different between the two.
LMDE5 is better. 
Isn't LM20.3 missing something? 
![スクリーンショット 2022-03-07 12-10-01](https://user-images.githubusercontent.com/78515193/156962041-ad21e691-9586-4bc1-80bc-c55187babfef.png)

**Comment by xenopeek** [comment]
LMDE 5 includes the new xapp-thumbnailer, which Linux Mint 21 will also get. It was developed after Linux Mint 20.3 so no it's not missing from there. See the latest monthly news: https://blog.linuxmint.com/?p=4285. In any case, not a LMDE 5 bug :)

**Comment by clefebvre** [comment]
ah I forgot I put it in LMDE 5 :)
