### ISSUE TITLE
A couple of failed edge use cases installing to multiple partitions

### ISSUE THREAD

**Issue by lumixdeee** [linuxmint/lmde-5-cinnamon-beta#37]
I've noted two situations that have failed in the past

Situation 1: 
Two disks, 1 and 2
Disk 1 has two partitions, a and b, disk 2 has one partition, A.

Install / to 1a
/usr to 2A
/usr/share to 1b

The install puts all of /usr in 2A and nothing in 1b

Situation 2:
Installing / to a 3.25GB partition, with 10 or more subfolders installed to partitions on a separate usb drive, not all of the 10 subfolders were mounted and used.

If either of these are of interest I can try to reproduce and document.

**Comment by clefebvre** [comment]
Please do, we'll need the installation output (run it in CLI mode via `sudo live-installer`).

**Comment by clefebvre** [comment]
If situation 1 is bugged, it's likely 2 is related. You can keep it simple by only documenting the first one.

**Comment by lumixdeee** [comment]
Situation 1 reproduced!
The install claims, correctly, to mount the /usr/share partition on disk one, but then copies nothing to it, copying all of /usr to partition 1 of disk 2

[5b37-moreinfo.txt](https://github.com/linuxmint/lmde-5-cinnamon-beta/files/8217024/5b37-moreinfo.txt)
[install-terminal-5b37.txt](https://github.com/linuxmint/lmde-5-cinnamon-beta/files/8217025/install-terminal-5b37.txt)
![Screenshot from 2022-03-09 17-05-08](https://user-images.githubusercontent.com/42706563/157502961-f9ca136f-356a-4343-9171-60678961e266.png)
.

Let me know if you need any more from this install, if not i'll format it to try to reproduce situation 2

**Comment by clefebvre** [comment]
thanks @minuxlintebiandedition I'll try to reproduce and troubleshoot tomorrow.
