### ISSUE TITLE
gnome-terminal cannot adjust opacity

### ISSUE THREAD

**Issue by lumixdeee** [linuxmint/lmde-5-cinnamon-beta#38]
The hint of opacity that comes with lmde terminal is slick and iconic. Where has it gone?

**Comment by clefebvre** [comment]
It was removed in mint-themes.

**Comment by lumixdeee** [comment]
Ability to adjust opacity is completely gone from gnome-terminal! Both in the lmde version and the gnome version? Why?

Is it safe, as in secure, to use an older version of gnome-terminal or is it safer to switch to mate-terminal latest version?

**Comment by clefebvre** [comment]
It's dictated by the theme. The theme has the ability to define the terminal back color and that can include transparency.

You can switch to mate-terminal if you want of course. As for older gnome-terminal versions it's up to you, check CVE just in case and changelogs.
