### ISSUE TITLE
system: Change mlocate with plocate

### ISSUE THREAD

**Issue by kelebek333** [linuxmint/lmde-5-cinnamon-beta#40]
Hi,

Could you change mlocate with plocate?

https://www.linuxuprising.com/2021/09/plocate-is-much-faster-locate-drop-in.html

**Comment by Jeremy7701** [comment]
Given that mlocate/plocate run as a background jobs, usually daily and the interactive locate command runs much faster than you can type the partial filename, there doesn't appear to be any overriding hurry to change this.

**Comment by clefebvre** [comment]
Fixed, plocate will be used in the stable release.

**Comment by vegam57** [comment]
It's fresh. Fun
If I automatically upgrade from Beta to stable version of LMDE5, 
will it automatically replace Mlocate with Plocate?

**Comment by kelebek333** [comment]
> Fixed, plocate will be used in the stable release.

Thanks.
