### ISSUE TITLE
Every time grub updates, grub resets branding to 'debian' instead of 'LMDE 5 elsie'

### ISSUE THREAD

**Issue by lumixdeee** [linuxmint/lmde-5-cinnamon-beta#42]
Every time grub updates, grub branding is reset to 'debian' instead of 'LMDE 5 elsie'

Reinstalling the debian-system-adjustments package fixes this.

**Comment by clefebvre** [comment]
Which branding in particular ?

**Comment by lumixdeee** [comment]
The boot menu, and after that when it says 'booting...'

I have removed plymouth and am using grub2-theme-mint 1.1 and sysvinit

**Comment by clefebvre** [comment]
update-grub brings back "Debian" into grub.cfg but this is overridden at shutdown/reboot and startup via systemd (/lib/systemd/system/debian-system-adjustments.service).
