### ISSUE TITLE
Chromium 90 from linxmint repo has dependency issues [32-bit]

### ISSUE THREAD

**Issue by enigma9o7** [linuxmint/lmde-5-cinnamon-beta#43]
If I try to install chromium from the software manager, it says "installing" forever, never reports an error or times out or completes, has to be aborted manually.

Looking at apt policy, it shows version 90 from linuxmint repo as highest priority, however it won't install due to dependency issues.

Version 99 from bullseye-security does install and work fine if forced with `sudo apt install -t bullseye-security chromium`
![Screenshot from 2022-03-08 16-49-48](https://user-images.githubusercontent.com/30579733/157484754-666c638d-3a41-4338-ade8-9fdd04be52a3.png)

This only affects 32-bit.  The 64-bit version has a chromium 99 in Mint repo that installs without issue.

**Comment by Jeremy7701** [comment]
What does `chromium --version` show?
In **LMDE4**, I get "Chromium 99.0.4844.51 for Linux Mint"

In LMDE5beta, I get
"Command 'chromium' not found, but can be installed with:
sudo apt install chromium", and doing so downloads:-
```
Get:1 https://deb.debian.org/debian bullseye/main amd64 libgl1-mesa-glx amd64 20.3.5-1 [51.1 kB]
Get:2 http://packages.linuxmint.com elsie/upstream amd64 chromium amd64 99.0.4844.51~linuxmint1+elsie [84.5 MB]
Fetched 84.6 MB in 24s (3,528 kB/s) 
```
`chromium --version` (in **LMDE5**) now shows "Chromium 99.0.4844.51 for Linux Mint"

**Comment by clefebvre** [comment]
Build updated.
