### ISSUE TITLE
hardware: Dual display

### ISSUE THREAD

**Issue by nogin1950** [linuxmint/lmde-5-cinnamon-beta#44]
Have migrated over to LMDE5  from LM 20.3 and can no longer display to monitors

**Comment by leigh123linux** [comment]
You fail to provide any useful info.

**Comment by nogin1950** [comment]
I get both displays on startup before i boot into LMDE5. After startup the IGU is not find in display settings.
I have used LM 20.3 and i get dual displays.
xrandr
HDMI-1 connected primary 1920x1080+0+0 (normal left inverted right x axis y axis) 596mm x 335mm
   3840x2160     30.00 +  30.00    25.00    24.00    29.97    23.98  
   2560x1600     59.97  
   2560x1440     59.95  
   1920x1080     60.00*   50.00    59.94    30.00    24.00    29.97    23.98  
   1920x1080i    60.00    50.00    59.94  
   DVI-0 disconnected (normal left inverted right x axis y axis)

![Screenshot from 2022-03-10 09-33-13](https://user-images.githubusercontent.com/65222753/157621152-d7438925-4922-491d-b293-3da4c16cab29.png)

**Comment by leigh123linux** [comment]
There still isn't enough info, post

```
inxi -GSC
```

**Comment by nogin1950** [comment]
What more info is required?

**Comment by leigh123linux** [comment]
Post the output for the command from my previous comment.

**Comment by nogin1950** [comment]
System:
  Host: hulen Kernel: 5.10.0-12-amd64 x86_64 bits: 64 
  Desktop: Cinnamon 5.2.7 Distro: LMDE 5 Elsie 
CPU:
  Info: Quad Core model: Intel Core i5-4460S bits: 64 type: MCP 
  L2 cache: 6 MiB 
  Speed: 857 MHz min/max: 800/3400 MHz Core speeds (MHz): 1: 857 2: 1149 
  3: 1292 4: 1007 
Graphics:
  Device-1: Intel Xeon E3-1200 v3/4th Gen Core Processor Integrated Graphics 
  driver: i915 v: kernel 
  Device-2: AMD Oland [Radeon HD 8570 / R5 430 OEM / R7 240/340 / Radeon 520 
  OEM] 
  driver: radeon v: kernel 
  Display: x11 server: X.Org 1.20.11 driver: loaded: ati,modesetting,radeon 
  unloaded: fbdev,vesa resolution: 1920x1080~60Hz 
  OpenGL: renderer: AMD OLAND (DRM 2.50.0 5.10.0-12-amd64 LLVM 11.0.1) 
  v: 4.5 Mesa 20.3.5

**Comment by penttila1** [comment]
I also recognized problems with dual displays on the 32 bit version of LMDE5 Beta.

When a second display (HP LA2006x) is connected via a VGA cable, after booting a dialogue is displayed saying 'the environment is running in reserved mode'. When clicking on 'restarting Cinnamon', Cinnamon is rebooted but the same error window is displayed as long I disconnect the second monitor.

[inxiHP.txt](https://github.com/linuxmint/lmde-5-cinnamon-beta/files/8231269/inxiHP.txt)

**Comment by clefebvre** [comment]
I'll close this since it doesn't lead to a bug fix resolution. It looks like a hardware support issue, I'd suggest troubleshooting it on the forums.
