### ISSUE TITLE
menu@cinnamon.org with Change categories on hover =OFF

### ISSUE THREAD

**Issue by vegam57** [linuxmint/lmde-5-cinnamon-beta#6]
Hi,
I am enjoying LMDE5 Beta.
I am happy with the good results.
But I want you to fix this.
https://github.com/linuxmint/cinnamon/issues/10573
Thank you. 

MintMenu of **Cinnamon 5.2.7 (LMDE5 beta)**
This issue is on an intel real machine.
No VM.

**Issue**
The focus will not be correct.
**Steps to reproduce**
Change categories on hover =OFF
and
If you use ↓ on the keyboard.

![MintMenu of Cinnamon](https://user-images.githubusercontent.com/78515193/156090063-32c295ca-3086-4172-86b2-48f51b811c04.gif)

**Comment by mtwebster** [comment]
This is already fixed by https://github.com/linuxmint/cinnamon/commit/d66ff9c88b0882fdba6a3a4d6c0f5de36393c593 - it hasn't been put in an update yet.
