### ISSUE TITLE
Not have "Check connectivity" setting item

### ISSUE THREAD

**Issue by vegam57** [linuxmint/lmde-5-cinnamon-beta#8]
LMDE5 does not have "Check connectivity" setting item.
Is this a natural result? 
Located in files/usr/share/cinnamon/cinnamon-settings/modules/cs_privacy.py:86 
![2022-03-01 16-56-02](https://user-images.githubusercontent.com/78515193/156129319-b0159f3d-2b31-4b4e-a1bd-704576dbb857.png)

**Comment by mtwebster** [comment]
Hi please run:
```
apt install network-manager-config-connectivity-debian
```
then reboot.

It looks like the url that's used to check connectivity is missing, and is provided by that package.

**Comment by vegam57** [comment]
> It looks like the url that's used to check connectivity is missing, and is provided by that package.

Hi
I got it.
If there is no problem with LMDE, please close this question. 
Thank you.

**Comment by clefebvre** [comment]
Package added in next ISO.
