### ISSUE TITLE
cursor become 'inactive/respondless' in Firefox - NVidia

### ISSUE THREAD

**Issue by penttila1** [linuxmint/lmde-5-cinnamon-beta#9]
To repeat the problem try to download the sha256sum.txt file of LM 20.3 Cinnamon 64 bit with Firefox (ver. 97.0.1)

1) Open https://www.linuxmint.com/edition.php?id=292 with Firefox. When hoovering the mouse over the 'active' elements of the page, the 'arrow' cursor correctly changes to a 'pointing hand' as recognizing them.

2) Right-click on sha256sum.txt and select 'Save link as'. Nothing happens! The cursor still can be moved around the screen but it does not recognize the 'active' elements anymore including the ones on the tray. Even Alt-Tab doesn't operate anymore. Sometime the 'Select the filename' window appears after several minutes and everything work fine again. Other times I have to use the 'Power off'  button as the system does not respond in any other way.

Notes:
- This happens also when downloading on other web sites.
- I had 'freezing' problems on the same hardware with LM 20.3 Cinnamon 64 bit too.

inxi -Fxxxrz:

System:
  Kernel: 5.10.0-11-amd64 x86_64 bits: 64 compiler: gcc v: 10.2.1 
  Desktop: Cinnamon 5.2.7 tk: GTK 3.24.24 wm: muffin 5.2.0 
  dm: LightDM 1.26.0 Distro: LMDE 5 Elsie base: Debian 11.2 bullseye 
Machine:
  Type: Desktop System: FUJITSU SIEMENS product: ESPRIMO E5625 v: N/A 
  serial: <filter> Chassis: type: 3 serial: <filter> 
  Mobo: FUJITSU SIEMENS model: D2724-A1 v: S26361-D2724-A1 serial: <filter> 
  BIOS: FUJITSU SIEMENS // Phoenix v: 6.00 R1.05.2724.A1 date: 06/26/2008 
CPU:
  Info: Dual Core model: AMD Athlon 64 X2 5000+ bits: 64 type: MCP 
  arch: K8 rev.F+ rev: 2 L2 cache: 1024 KiB 
  flags: lm nx pae sse sse2 sse3 svm bogomips: 10400 
  Speed: 1000 MHz min/max: 1000/2600 MHz Core speeds (MHz): 1: 1000 2: 1000 
Graphics:
  Device-1: NVIDIA C77 [GeForce 8200] vendor: Fujitsu Solutions 
  driver: nouveau v: kernel bus ID: 02:00.0 chip ID: 10de:084b 
  class ID: 0300 
  Display: x11 server: X.Org 1.20.11 driver: loaded: modesetting 
  unloaded: fbdev,vesa resolution: 1280x1024~60Hz s-dpi: 96 
  OpenGL: renderer: NVAA v: 3.3 Mesa 20.3.5 direct render: Yes 
Audio:
  Device-1: NVIDIA MCP72XE/MCP72P/MCP78U/MCP78S High Definition Audio 
  vendor: Fujitsu Solutions driver: snd_hda_intel v: kernel bus ID: 00:07.0 
  chip ID: 10de:0774 class ID: 0403 
  Sound Server: ALSA v: k5.10.0-11-amd64 
Network:
  Device-1: Broadcom NetLink BCM5787 Gigabit Ethernet PCI Express 
  vendor: Fujitsu Solutions driver: tg3 v: kernel port: 4000 bus ID: 05:00.0 
  chip ID: 14e4:169b class ID: 0200 
  IF: enp5s0 state: up speed: 1000 Mbps duplex: full mac: <filter> 
Drives:
  Local Storage: total: 74.53 GiB used: 6.31 GiB (8.5%) 
  ID-1: /dev/sda vendor: Seagate model: ST380815AS size: 74.53 GiB 
  speed: 3.0 Gb/s serial: <filter> rev: A scheme: MBR 
Partition:
  ID-1: / size: 71.06 GiB used: 6.18 GiB (8.7%) fs: ext4 dev: /dev/sda2 
Swap:
  ID-1: swap-1 type: partition size: 1.77 GiB used: 139.8 MiB (7.7%) 
  priority: -2 dev: /dev/sda1 
Sensors:
  System Temperatures: cpu: 34.0 C mobo: N/A gpu: nouveau temp: 68.0 C 
  Fan Speeds (RPM): N/A 
Repos:
  Packages: apt: 2011 
  No active apt repos in: /etc/apt/sources.list 
  Active apt repos in: /etc/apt/sources.list.d/official-package-repositories.list 
  1: deb https://quantum-mirror.hu/mirrors/linuxmint/packages elsie main upstream import backport
  2: deb https://deb.debian.org/debian/ bullseye main contrib non-free
  3: deb https://deb.debian.org/debian/ bullseye-updates main contrib non-free
  4: deb http://security.debian.org/ bullseye-security main contrib non-free
  5: deb https://deb.debian.org/debian/ bullseye-backports main contrib non-free
Info:
  Processes: 175 Uptime: 2h 15m wakeups: 0 Memory: 1.69 GiB 
  used: 781.6 MiB (45.2%) Init: systemd v: 247 runlevel: 5 Compilers: 
  gcc: 10.2.1 alt: 10 Shell: Bash v: 5.1.4 running in: gnome-terminal 
  inxi: 3.3.01

**Comment by mtwebster** [comment]
The way you describe it's all about waiting for the save dialog to pop up (this explains everything becoming unresponsive as well).  Is your 'default' save directory a local folder. Do you have any bookmarks or locations that usually populate the sidebar of the save dialog that are remote mounts?

Can you run firefox from a terminal and see if there are any warnings or errors?  Allow the wait to complete (if it eventually shows the dialog).

**Comment by penttila1** [comment]
The answers:

1a) Yes, it is the default 'download' directory on the local disk.
1b) No, it is a simple PC with a single local disk as the LMDE default installation procedure prepared it, nothing remote.

2) I attach the copy of the terminal output. It contains four runs. The first didn't produced any output, while there were two of them which complained about lost messages. As I remember these happened when I closed the Firefox program.
The third one, with a long driver output, happened when I closed the save dialog by the 'X' at its top right corner.
[The translation of "Az eszköz vagy erőforrás foglalt" is: The device or resource is occupied (busy).]

At the first run I had to wait more than five minutes for the appearance of the dialog. At the subsequent runs the dialog appeared normally / immediately. 

Another observation: once, when closing Firefox with "X" at https://www.linuxmint.com/edition.php?id=292, the Firefox window was properly closed but I haven't got back the prompt in the terminal. I tried to kill the firefox-bin process with the 'system monitoring tool' but I didn't succeed! I had to close the terminal to get rid of the running Firefox. Have a look at the attached screenshot, specially on firefox-bin process which has very interesting data.

[terminal.txt](https://github.com/linuxmint/lmde-5-cinnamon-beta/files/8169421/terminal.txt)
![Screenshot](https://user-images.githubusercontent.com/54205839/156359446-738e349d-9eec-4cf8-a50f-df2b2ced9dae.png)

**Comment by mtwebster** [comment]
I think that's a zombie process. I assume you've rebooted at some point while experiencing this problem? If so I probably wouldn't worry about it for now (I have a zombie firefox-bin in my proc list as well right now) - you can verify by running `ps -A | grep firefox` - one of them will say '\<defunct>\'.

Something else to try - please run:
```
GIO_USE_VFS=local firefox
```

Also, does nemo (files) open normally? If you run `xed` then try to save a text file, does that dialog appear immediately?

**Comment by penttila1** [comment]
First I rebooted the PC.

1) with "GIO_USE_VFS=local firefox" I can't see any difference in behaving, even when closing Firefox with "X", I got the same 'lost message' error.

2) I played around with Nemo but I couldn't recognize any problem. It was fast and reactive.

3) the save dialog at xed appears normally, immediately. File saving works, nothing appears in the terminal.

Please don't forget to check the terminal.txt file in my previous comment!

**Comment by penttila1** [comment]
### Some other observations on the same hw but testing just the LIVE version without installation:

1) This 'sleeping and wake up after some time' state can happen:
   a) just by scrolling up and down with mouse wheel in Firefox on linuxmint.com page on a freshly loaded LMDE
   b) by 'save as' in xed (only once)

2) sometime the when hoovering over the active and passive elements in firefox the shape of mouse pointing icon is mixed up. It changes to 'hand' or 'adjust the side of window' on passive parts while shows 'simple arrow' on active ones.

3) sometime when hoovering over the active/passive elements on the screen only the ones in firefox window gets this unresponsive state, the other ones e.g. on the task bar remain active and work fine.

4) sometime when trying to kill firefox with the task manager I got a "Mozilla Firefox is not responding" message

### Other tests, info:

1) I was playing around on the same hw (but with the installed version of LMDE) using Chromium and I haven't recognized any problem and was not able to reproduce any of the previously reported bugs. (Chromium reported some errors in its terminal output.)

2) I also tested somehow this LMDE version in LIVE mode on a Dell Latitude E5400 laptop (with Intel Mobile 4 series chipset integrated) but I haven't find any problem.

**Comment by mtwebster** [comment]
> Please don't forget to check the terminal.txt file in my previous comment!

I did  - there was nothing useful, unfortunately.

Can you run the program `top` and upload a screenshot of it while you're having this issue? I'm wondering if you're running up against your limited system resources (2gb ram, dual core) - this should be enough to run without too many issues, but firefox can be hungry.

firefox vs chromium, 5 tabs open, all same content:

![image](https://user-images.githubusercontent.com/262776/156584308-2c88c88e-211c-4b2f-81a7-5d796f252701.png)

**Comment by penttila1** [comment]
I don't know what you exactly mean on the screenshot of top but I tried to do something useful.

1) created a screenshot of system monitoring while reproducing the problem

2) running top in a terminal with redirected output to a file (top >>top.txt). These show dynamicaly what is happening, which can be useful. Firefox memory usage seems to be constant but why does Firefox and Xorg consume sometime 40% CPU? I attach four runs of top, the fourth seems to be the best to analyze.

![screenshot](https://user-images.githubusercontent.com/54205839/156777430-1b7ca053-1b61-4f70-b2ca-c142da61903e.png)
[top1.txt](https://github.com/linuxmint/lmde-5-cinnamon-beta/files/8186405/top1.txt)
[top2.txt](https://github.com/linuxmint/lmde-5-cinnamon-beta/files/8186406/top2.txt)
[top3.txt](https://github.com/linuxmint/lmde-5-cinnamon-beta/files/8186407/top3.txt)
[top4.txt](https://github.com/linuxmint/lmde-5-cinnamon-beta/files/8186408/top4.txt)

**Comment by mtwebster** [comment]
Ah sorry, I meant run `top`, then just take a screenshot of the terminal while it's running.

Xorg is running the entire session, and all hardware works thru it - if something video-intensive is running, its cpu use will increase also.

Have you tried installing the nvidia driver for your graphics card?

Also, please attach your `~/.xsession-errors` file.

**Comment by penttila1** [comment]
1) I couldn't take a screenshot of top during the problem repetition as the system has been frozen.

2) I attach xsession-errors.old for yesterday and xsession-errors-nouveau for today.

3) I don't know how to install a new driver on LMDE (as this is my first experience with LMDE). As I remember I installed the recommended nvidia driver also with LinuxMint 20.3 Cinnamon on this hardware and find the same problematic behavior. If you want I can install LM 20.3 and test it again.

[xsession-errors.old.txt](https://github.com/linuxmint/lmde-5-cinnamon-beta/files/8191136/xsession-errors.old.txt)
[xsession-errors-nouveau.txt](https://github.com/linuxmint/lmde-5-cinnamon-beta/files/8191137/xsession-errors-nouveau.txt)

**Comment by penttila1** [comment]
Finally I find some description on installing drivers on Debian, so I tried to do it. Unfortunately nvidia-detect says - according to my understanding - that my video card is not supported anymore as 'buster' means Debian 10.

![nvidia-detect](https://user-images.githubusercontent.com/54205839/156930382-4acc99db-c1fe-4171-b88f-595d87a46b4f.png)

**Comment by mtwebster** [comment]
Can you try:
```
killall nemo
killall nemo-desktop
killall nemo-desktop # yes twice
killall gvfsd-trash
```

Then try firefox (after restarting it)

**Comment by penttila1** [comment]
After rebooting LMDE I repeated the requested command sequence - see the screenshot - twice, separated by a dashed line.

In the first run - after 'saving link as' - the dialogue opened relative fast but soon the cursor became irresponsible as before, while in the second run the cursor freezed before the dialogue appeared but only for a relative short time. It was also interesting to see that Firefox had no output in the terminal.

translation: 'nem található folyamat' means 'no such process'/'process not found'.

![killall](https://user-images.githubusercontent.com/54205839/157267600-408d6c0b-411f-4a97-b2bd-3ef3b67800b5.png)

**Comment by mtwebster** [comment]
Ok, that's sort of interesting.

One more thing to try:
```
mv /usr/libexec/gvfsd-trash /usr/libexec/gvfsd-trash.bak
killall gvfsd-trash
```

**Comment by penttila1** [comment]
I continued the tests with your new commands and repeated them twice.

first run: after 'save link as' the dialogue opened quite fast and the system was behaving well even after it.

second run (I repeated the last two command but they failed and than reopened Firefox): after 'save link as' the cursor became irresponsible again forever. After 24 minutes waiting I powered off the PC.

**Comment by penttila1** [comment]
Some more info:

I installed LinuxMint 20.3 Cinnamon 64 bit on the same PC. Without updating the packages, Firefox behaved in the same 'unresponsive' way when 'saving link as' with the original 'nouveau' driver. After changing the driver to the recommended nvidia-340 (340.108-Oubuntu5.20.04.2), I was not able to stand up the system as after login the screen collapsed and began to flickering.

**Comment by mtwebster** [comment]
Just curious, have you ever tried xfce or mate? They are  a lot less graphics-intensive, and generally lighter weight. I'm just curious if the problem might be Cinnamon specifically.

**Comment by penttila1** [comment]
I installed linuxmint-20.3-xfce-64bit on my problematic hardware and was not able to reproduce the 'save link as' problem neither on the live nor on the installed version with the default nouveau driver. You may be right that it is Cinnamon specific. If so, than this is an even more important, valuable info for you.

Yes, I know about the XFCE versions and I always use them on still existing 32 bit hardwares. That is why it is a real pain for me that LMDE does not have XFCE versions anymore for really old PCs!

**Comment by penttila1** [comment]
I also tested lmde-5-cinnamon-32bit-beta in a live mode on my problematic hardware and I got the same problems while 'saving link as'.

**Comment by mtwebster** [comment]
You can install the `xfce4` package in lmde5 to get that desktop (though these are *debian* packages, not Mint, for what it's worth.

Otherwise, I don't think we'll hold up lmde5 for this. I will keep an eye and see if I can reproduce the lag issue though.

Thanks
